import type { Framework } from "@/lib/types";

export const frameworks: Framework[] = [
  {
    id: 1,
    name: "Meta Ad Scaling Framework",
    category: "ads",
    purpose: "Improve Facebook and Instagram ad performance.",
    bestFor: "Businesses running or planning Meta ads.",
    focusAreas: ["Hook", "Creative", "Offer", "Audience targeting", "Landing page", "Retargeting"],
    aiInstructions: "Prioritize Meta channel performance gains, creative testing, and audience-to-offer alignment.",
  },
  {
    id: 2,
    name: "Google Search Domination Framework",
    category: "ads",
    purpose: "Generate high-intent leads through Google Ads.",
    bestFor: "Businesses whose customers actively search for their service.",
    focusAreas: ["Keywords", "Search intent", "Ad copy", "Landing page relevance", "Conversion tracking", "Budget allocation"],
    aiInstructions: "Focus on search demand capture, query intent, and conversion-efficient ad spend.",
  },
  {
    id: 3,
    name: "Creative Optimization Framework",
    category: "ads",
    purpose: "Improve click-through rates through stronger ad creatives.",
    bestFor: "Businesses getting impressions but weak clicks.",
    focusAreas: ["Visuals", "Video hooks", "Copywriting", "Social proof", "Testing angles", "Creative fatigue"],
    aiInstructions: "Recommend creative experimentation to increase CTR and reduce fatigue-driven performance decline.",
  },
  {
    id: 4,
    name: "Offer Optimization Framework",
    category: "ads",
    purpose: "Improve conversions by making the offer more attractive.",
    bestFor: "Businesses with weak, unclear, or boring offers.",
    focusAreas: ["Core promise", "Discount structure", "Bonuses", "Guarantee", "Urgency", "Differentiation"],
    aiInstructions: "Emphasize offer clarity, perceived value, and conversion-driving differentiation tactics.",
  },
  {
    id: 5,
    name: "Landing Page Conversion Framework",
    category: "ads",
    purpose: "Turn more ad clicks into leads or customers.",
    bestFor: "Businesses getting clicks but poor conversions.",
    focusAreas: ["Headline", "Page speed", "Call-to-action", "Trust signals", "Form design", "Mobile experience"],
    aiInstructions: "Address conversion leaks on-page and prioritize rapid testing around UX and trust.",
  },
  {
    id: 6,
    name: "Retargeting Profit Framework",
    category: "ads",
    purpose: "Recover lost prospects through retargeting.",
    bestFor: "Businesses with website traffic or ad engagement but low follow-up.",
    focusAreas: ["Warm audiences", "Abandoned leads", "Follow-up ads", "Testimonials", "Scarcity", "Re-engagement"],
    aiInstructions: "Design retargeting loops that reactivate warm traffic and recover lost conversion opportunities.",
  },
  {
    id: 7,
    name: "Local SEO Domination Framework",
    category: "seo",
    purpose: "Increase visibility in Google Maps and local search.",
    bestFor: "Local service businesses.",
    focusAreas: ["Local keywords", "Service pages", "Location pages", "Citations", "Google Maps", "Competitor gaps"],
    aiInstructions: "Prioritize local intent coverage, map pack visibility, and geo-targeted content structure.",
  },
  {
    id: 8,
    name: "Google Business Profile Framework",
    category: "seo",
    purpose: "Optimize a Google Business Profile for more calls and leads.",
    bestFor: "Businesses with weak or incomplete Google profiles.",
    focusAreas: ["Categories", "Services", "Photos", "Posts", "Reviews", "Q&A"],
    aiInstructions: "Recommend operational improvements inside GBP that increase trust and lead actions.",
  },
  {
    id: 9,
    name: "Authority Content Framework",
    category: "seo",
    purpose: "Build ranking power through helpful content.",
    bestFor: "Businesses that need long-term organic growth.",
    focusAreas: ["Blog topics", "Service content", "Buyer questions", "Internal linking", "Topical authority", "Content calendar"],
    aiInstructions: "Map content strategy to buyer intent and topical depth with consistent publishing.",
  },
  {
    id: 10,
    name: "Technical SEO Framework",
    category: "seo",
    purpose: "Fix technical issues preventing search visibility.",
    bestFor: "Businesses with slow, broken, or poorly structured websites.",
    focusAreas: ["Site speed", "Indexing", "Metadata", "Schema", "Mobile usability", "Crawl errors"],
    aiInstructions: "Highlight technical blockers and sequence remediation by impact on crawlability and rankings.",
  },
  {
    id: 11,
    name: "Review Growth Framework",
    category: "seo",
    purpose: "Increase trust and local ranking power through reviews.",
    bestFor: "Businesses with few reviews or weak reputation.",
    focusAreas: ["Review requests", "Review response strategy", "Testimonials", "Social proof", "Reputation repair", "Review velocity"],
    aiInstructions: "Design scalable review acquisition and response systems to improve trust and local SEO signals.",
  },
  {
    id: 12,
    name: "Competitor SEO Gap Framework",
    category: "seo",
    purpose: "Identify and beat competitors in organic search.",
    bestFor: "Businesses trying to outrank local or niche competitors.",
    focusAreas: ["Competitor keywords", "Backlinks", "Content gaps", "Review gaps", "Service page gaps", "Ranking opportunities"],
    aiInstructions: "Use competitor gap analysis to prioritize the highest-leverage ranking opportunities.",
  },
  {
    id: 13,
    name: "Lead Generation Framework",
    category: "hybrid",
    purpose: "Increase total qualified lead flow.",
    bestFor: "Businesses that simply need more opportunities.",
    focusAreas: ["Target customer", "Lead sources", "Offer strategy", "Outreach", "Ads", "SEO"],
    aiInstructions: "Balance paid and organic channels to increase qualified lead volume without sacrificing quality.",
  },
  {
    id: 14,
    name: "Business Growth Framework",
    category: "hybrid",
    purpose: "Identify the highest-impact path to revenue growth.",
    bestFor: "Businesses unsure what their main bottleneck is.",
    focusAreas: ["Revenue bottlenecks", "Market positioning", "Lead flow", "Sales conversion", "Retention", "Operations"],
    aiInstructions: "Diagnose the primary growth constraint and propose the strongest cross-channel path to scale.",
  },
  {
    id: 15,
    name: "Conversion Optimization Framework",
    category: "hybrid",
    purpose: "Convert more prospects into paying customers.",
    bestFor: "Businesses getting leads but not enough sales.",
    focusAreas: ["Sales process", "Objections", "Landing pages", "Trust signals", "Follow-up", "Closing strategy"],
    aiInstructions: "Improve conversion outcomes by aligning sales process, messaging, and follow-up execution.",
  },
  {
    id: 16,
    name: "Marketing Funnel Framework",
    category: "hybrid",
    purpose: "Improve every step from awareness to purchase.",
    bestFor: "Businesses with disconnected marketing efforts.",
    focusAreas: ["Awareness", "Lead capture", "Nurture", "Conversion", "Follow-up", "Retention"],
    aiInstructions: "Connect funnel stages end-to-end to remove friction and improve progression rates.",
  },
  {
    id: 17,
    name: "Customer Retention Framework",
    category: "hybrid",
    purpose: "Increase repeat customers and lifetime value.",
    bestFor: "Businesses with past customers but weak follow-up.",
    focusAreas: ["Customer experience", "Loyalty offers", "Referral systems", "Reactivation", "Email campaigns", "Upsells"],
    aiInstructions: "Prioritize retention systems that lift repeat purchase rate, referrals, and customer lifetime value.",
  },
  {
    id: 18,
    name: "Automation Framework",
    category: "hybrid",
    purpose: "Save time and prevent missed opportunities.",
    bestFor: "Businesses wasting time on repetitive tasks or manual follow-up.",
    focusAreas: ["CRM", "Lead follow-up", "Appointment booking", "Email automation", "AI assistants", "Reporting"],
    aiInstructions: "Recommend process automation that increases speed-to-lead and consistency across customer touchpoints.",
  },
];
